apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "capa.fullname" . }}-controller-manager
  labels:
    cluster.x-k8s.io/provider: bootstrap-eks
    control-plane: controller-manager
  {{- include "capa.labels" . | nindent 4 }}
  annotations:
    ${AWS_CONTROLLER_IAM_ROLE/#arn/eks.amazonaws.com/role-arn: arn}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "capa.fullname" . }}-controller-manager
  labels:
    cluster.x-k8s.io/provider: bootstrap-eks
    control-plane: controller-manager
  {{- include "capa.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controllerManager.replicas }}
  selector:
    matchLabels:
      cluster.x-k8s.io/provider: bootstrap-eks
      control-plane: controller-manager
    {{- include "capa.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        cluster.x-k8s.io/provider: bootstrap-eks
        control-plane: controller-manager
      {{- include "capa.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - args:
        - --metrics-addr=127.0.0.1:8080
        - --enable-leader-election
        - --feature-gates=MachinePool={{ default false .Values.providerArgs.machinePool }}
        command:
        - /manager
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ .Values.kubernetesClusterDomain }}
        image: {{ .Values.controllerManager.manager.image.repository }}:{{ .Values.controllerManager.manager.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: IfNotPresent
        name: manager
        resources: {}
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ .Values.kubernetesClusterDomain }}
        image: {{ .Values.controllerManager.kubeRbacProxy.image.repository }}:{{ .Values.controllerManager.kubeRbacProxy.image.tag
          | default .Chart.AppVersion }}
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
        resources: {}
      securityContext:
        fsGroup: 1000
      serviceAccountName: {{ include "capa.fullname" . }}-controller-manager
      terminationGracePeriodSeconds: 10
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master